on:
  push:
    branches:
      - docs
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Doxygen docs
      id: ghaction
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: doc/doxygen
        doxyfile-path: ./doxyfile
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/doxygen/html